GET http://localhost:3000/ad

####

GET http://localhost:3000/ad?category=vêtement

####

POST http://localhost:3000/ad
Content-Type: application/json

{
        "title": "Manette Xbox",
        "description":
          "Ma Manette Xbox working fine",
        "owner": "bike.seller@gmail.com",
        "price": 40,
        "picture":
          "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
        "location": "Toulouse",
        "createdAt": "2023-09-05T10:13:14.755Z",
        "category": 5,
        "tag": [{"id": 1}, {"id": 2}]
}

####

DELETE http://localhost:3000/ad/25

####
PUT http://localhost:3000/ad/16
Content-Type: application/json

{
  "picture": "https://m.media-amazon.com/images/I/71PFaWU6AaL._AC_UF1000,1000_QL80_.jpg"
}