GET http://localhost:3000/ad

####

GET http://localhost:3000/ad/title?title=poul

####

GET http://localhost:3000/ad/category?category=voiture

####

GET http://localhost:3000/ad/tag?tag=Promotion

####

GET http://localhost:3000/ad?category=voiture

####

POST http://localhost:3000/ad
Content-Type: application/json

{
        "title": "Manette Xbox",
        "description":
          "Ma Manette Xbox working fine",
        "owner": "bike.seller@gmail.com",
        "price": 40,
        "picture":
          "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
        "location": "Toulouse",
        "createdAt": "2023-09-05T10:13:14.755Z",
        "category": 5,
        "tag": [{"id": 1}, {"id": 2}]
}

####

DELETE http://localhost:3000/ad/2

####
PUT http://localhost:3000/ad/1
Content-Type: application/json

{
    "picture": "https://www.cube-protection.fr/38958-large_default/blouson-a-capuche-hiver-homme-bartlett-carhartt-103826.jpg"
}