GET http://localhost:3000/ads

####

GET http://localhost:3000/ads?category=informatique

####

POST http://localhost:3000/ads
Content-Type: application/json

{
        "title": "HeadSet",
        "description":
          "My HeadSet working fine",
        "owner": "bike.seller@gmail.com",
        "price": 75,
        "picture":
          "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
        "location": "Toulouse",
        "createdAt": "2023-09-05T10:13:14.755Z"
}

####

DELETE http://localhost:3000/ads/25

####
PUT http://localhost:3000/ads/23
Content-Type: application/json

{
        "price": 175,
        "category": 3
}