GET http://localhost:3000/category

####

GET http://localhost:3000/category?title=m

####

POST http://localhost:3000/category
Content-Type: application/json

{
    "title": "électro-ménager"
}

####

DELETE http://localhost:3000/category/9

####

PUT http://localhost:3000/category/5
Content-Type: application/json

{
    "title": "meubles"
}