GET http://localhost:3000/category

####

GET http://localhost:3000/category?title=vê

####

POST http://localhost:3000/category
Content-Type: application/json

{
    "title": "électro-ménager"
}

####

DELETE http://localhost:3000/category/7

####

PUT http://localhost:3000/category/3
Content-Type: application/json

{
    "title": "informatique"
}