GET http://localhost:3000/ads

####

GET http://localhost:3000/ads?location=Paris


####

POST http://localhost:3000/ads
Content-Type: application/json

{
        "title": "Printer",
        "description":
          "My print",
        "owner": "bike.seller@gmail.com",
        "price": 350,
        "picture":
          "https://images.lecho.be/view?iid=dc:113129565&context=ONLINE&ratio=16/9&width=640&u=1508242455000",
        "location": "Toulouse",
        "createdAt": "2023-09-05T10:13:14.755Z",
        "category_id": 3
}

####

DELETE http://localhost:3000/ads/19

####
PUT http://localhost:3000/ads/20
Content-Type: application/json

{
        "price": 50
}